// Dataset selector shim — do NOT put prospect data in this file.
// College data lives in prospects.college.ts (see prospects.example.ts),
// redraft data in prospects.redraft.ts (generated by scripts/generate-redraft-dataset.ts).
import { Prospect } from '../engine/types';
import { DRAFT_MODE } from './draftMode';
import { PROSPECTS as COLLEGE_PROSPECTS } from './prospects.college';
import { REDRAFT_PROSPECTS } from './prospects.redraft';

export const PROSPECTS: Prospect[] =
  DRAFT_MODE === 'redraft' ? REDRAFT_PROSPECTS : COLLEGE_PROSPECTS;

// De-duplicate by rank (safety net)
const seen = new Set<number>();
export const PROSPECTS_DEDUPED = PROSPECTS.filter(p => {
  if (seen.has(p.rank)) return false;
  seen.add(p.rank);
  return true;
});

export const PROSPECT_BY_RANK = new Map<number, Prospect>(
  PROSPECTS_DEDUPED.map(p => [p.rank, p])
);

export const ALL_POSITIONS = [...new Set(PROSPECTS_DEDUPED.map(p => p.pos))].sort();
